### ISSUE TITLE
Indoor drift for manual control M100

### ISSUE THREAD

**Issue by varununayak** [ethz-asl/mav_dji_ros_interface#22]
There's considerable drift in the M100 while flying indoors with A-mode on (manual control). Usually, we solve it using trimming in standard RCs. How can this problem be solved in the M100? I have already tried IMU recalibration. Any software fix?

**Comment by inkyusa** [comment]
Hi,
This could happen due to many sources (unbalanced M100, IMU and compass calibration, firmware ...).
If your drone doesn't carry serious payloads (e.g., just finished M100 assembly), try to check as follow;
First, please check the firmware version and we are using V.1.3.1.00 (you can find the version via https://github.com/ethz-asl/mav_dji_ros_interface/wiki/N1-Autopilot-firmware-check-and-lightbridge2-pairing)
Second, try to calibrate IMU and compass in OUTDOOR whether gentle wind and not strong magnetic interference. Of course, it won't drift much as indoor due to GPS update but bring it back to indoor and testing it.

As you mentioned, there is no trimming on the DJI remote and we don't know how this works.

**Comment by inkyusa** [comment]
I will close this issue since haven't heard for a while. Please re-open this if there exists any other similar issue.
