### ISSUE TITLE
RAM listed in Parts List is not compatible with NUC7i7BNH 3.5GHz i7-7567U

### ISSUE THREAD

**Issue by sfmig** [ethz-asl/mav_dji_ros_interface#24]
The RAM listed in the Parts List section is DDR3/DDR3L, whereas the NUC7i7BNH requires DDR4 memory.
Here's the link with the memory requirements for NUC7i7BNH:
[https://www.intel.com/content/www/us/en/support/articles/000023165/mini-pcs/intel-nuc-kits.html](url)

Thanks

**Comment by inkyusa** [comment]
Hi sfmig,
Thank you for your comment and you were right as described: https://www.intel.com/content/www/us/en/support/articles/000023165/mini-pcs/intel-nuc-kits.html
This happened due to a miss-matched NUC model number. Intel NUC 5i7RYH was the one we used for this project as described in https://github.com/ethz-asl/mav_dji_ros_interface/wiki/Hardware-and-Software-Versions
I updated the part list accordingly. If one wants to use a higher-performance NUC (e.g., NUC7i7BNH), it is recommended to find the correct combination of RAM, SSD, and etc.
