### ISSUE TITLE
Clarification regarding DJI onboard SDK

### ISSUE THREAD

**Issue by sfmig** [ethz-asl/mav_dji_ros_interface#25]
Hi,
In the [Hardware and Software versions page](https://github.com/ethz-asl/mav_dji_ros_interface/wiki/Hardware-and-Software-Versions), the official ROS packages for DJI onboard SDK is not included in the list, but later in the [N1 Autopilot section](https://github.com/ethz-asl/mav_dji_ros_interface/wiki/N1-Autopilot), the [MPC with MSF and ROVIO section](https://github.com/ethz-asl/mav_dji_ros_interface/wiki/MPC-with-MSF-and-ROVIO) and some others later, the dji-sdk package is mentioned in some of the commands (e.g. $roslaunch **dji_sdk** Onboard_exp_with_zr300_rw_indoor_falcon2.launch). I understand the official ROS package from DJI is then required, is that right? Or is it that the commands are maybe outdated? I saw in the [deprecated repo](https://github.com/ethz-asl/dji_onboard_sdk_ros) there was a ROS package called dji_sdk.

Thanks in advance

**Comment by inkyusa** [comment]
Hello sfmig,
Thank you for the catch, and this happens due to the deprecated repo you mentioned. Hopefully, it fixed correctly, please find my response to your questions;

> I understand the official ROS package from DJI is then required, is that right?
No, you don't need the official ROS package because this repo, mav_dji_ros_interface, already contains some packages of DJI SDK (e.g., dji_sdk_lib, dji_comm, and dji_interface). We stripped off unnecessary packages from the official DJI SDK and have tried to maintain minimum packages for sending commands and receiving sensors data (IMU only). 
The objective is minimizing efforts for utilizing ETH ASL's software packages (such as MPC, Rovio, MSF, Trajectory gen.) with DJI's drones by bridging the interface gap between Astech drones (what we are using) and DJI drones. But if you need more DJI-sh functionalities, I would recommend to use DJI-SDK from https://github.com/dji-sdk/Onboard-SDK-ROS. As a research lab, and considering relatively small project scope, we don't have human resources to catch up with DJI's frequent release updates.

**Comment by sfmig** [comment]
Thank you!
