### ISSUE TITLE
Continues rotating when takeoff at low speed

### ISSUE THREAD

**Issue by fx815** [ethz-asl/mav_dji_ros_interface#31]
I have successfully implemented the whole system following the wiki with vicon. 
When I take off using Poses mode or Polynomial trajectory with a higher speed, everything seems perfect. However, when I try to take off at low speed, say I set the intermediate point separation at 0.01, it takes off slowly, but somehow begin to rotate continuously. I check the current_reference and roll_pitch_yawrate_thrust topics, the reference yaw is right and not changing, but the yawrate given by nMPC have a constant 1.5 value, then gradually decease to 0, then constant 1.5 again. If I turn the serial switch off and on again, it can go back to normal and stop rotating, but even this trick doesn't always work. 
Any ideas of why this is happening and possible solutions?
Thanks!

**Comment by inkyusa** [comment]
Hello fx815,
Great to hear that you managed to make your drone work!

Did you send trajectories or a goal point via rqt topic publisher? If you haven't tested the latter, I recommend to test it (let's say sending 0, 0, 0.5 for x, y, z and leave rotation 0 0 0 1 ), as described in https://github.com/ethz-asl/mav_dji_ros_interface/wiki/First-Autonomous-Flight%3A-Hover-and-Step-Response.

If step response test works as expected (no rotating), then there may be some issues with the Polynomial trajectory publisher. Otherwise, some issues in the nMPC or other places.
Best,
Inkyu

**Comment by fx815** [comment]
Hi Inkyu,

I did try that before, and it worked. I suspect the rotating has something to do with the nmpc or disturbance observer. The drone I used was basically overloaded, it's quite heavy, plus the ground effect, I think it's quite hard for nmpc to control it takeoff as a low speed,say 1cm/s. When the drone is supposed to be off ground, the landing gear may still touch the ground, which may mess up the disturbance observer or nmpc somehow? The polynomial and poses topics are correct but the rollpitchyawratethrust topic given by nmpc has abnormal yaw rate values.
What do you think?

Best,
Feng
